services:
  server:
    image: aphireak-frontend
    build: ./frontend
    ports: 
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
  backend:
    image: aphireak-backend
    build: ./server
    environment:
      jwt.secret: javainuse
      spring.datasource.url: jdbc:postgresql://postgres:5432/
      spring.datasource.username: postgres
      spring.datasource.password: password
    depends_on:
      - postgres
    restart: "always"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./server/postgres/:/docker-entrypoint-initdb.d
    restart: "always"
