services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./postgres/:/docker-entrypoint-initdb.d
