services:
  backend:
    image: aphireak-backend
    build: .
    ports:
      - 8080:8080
    environment:
      jwt.secret: javainuse
      spring.datasource.url: jdbc:postgresql://postgres:5432/
      spring.datasource.username: postgres
      spring.datasource.password: password
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d
